### ISSUE TITLE
i need to make scheduler for twitter for multiple user is this script work ?

### ISSUE THREAD

**Issue by kalpeshbeit** [pablowright/AutoTweet#3]

**Comment by pablowright** [comment]
This script will very easily support as many Twitter users as you like. You just need to set up an API account for each Twitter user you wish to add. You will need to do this to create the tokens necessary for the script to post to Twitter for you. There are tutorials all over the Net on how to do this.

Once you have the users/tokens, you can add them to your database. Look at the sql.txt file for the database structure/example.

Hope this helps.
P
